In [ ]:
# @title Simple neural network with 5 input features and 1 output feature

In [3]:
#create model class
import torch
import torch.nn as nn

#this model doesn't have a hidden layer

class Model(nn.Module):  #nn.Module is the base class and must be inherited
  def __init__(self,num_features): #input number of feautres as a parameter

    super().__init__()  #calls the constructer of the parent class (calls the constructor of nn.Module)
    self.linear = nn.Linear(num_features, 1) #self.linear - named attribute of the model, mention the number of input and output features
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):

    out = self.linear(features)
    out = self.sigmoid(out)
    return out
    #apply the linear model and the sigmoid function to the features and store the output in out variable

In [4]:
#create dataset
features = torch.rand(10,5)

#create model
model = Model(features.shape[1]) #since the number of input features are 5

#call for forward pass
#model.forward(features)
model(features) # standard way of calling forward

tensor([[0.6640],
        [0.7071],
        [0.7506],
        [0.6988],
        [0.7338],
        [0.6556],
        [0.6657],
        [0.6976],
        [0.7157],
        [0.6332]], grad_fn=<SigmoidBackward0>)

In [5]:
#show model weights
model.linear.weight

Parameter containing:
tensor([[ 0.3654,  0.0719,  0.3592,  0.3381, -0.2896]], requires_grad=True)

In [6]:
model.linear.bias

Parameter containing:
tensor([0.3569], requires_grad=True)

In [7]:
!pip install torchinfo

In [8]:
from torchinfo import summary
summary(model, input_size = (10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [ ]:
# @title More complex netork with 5 inputs, hidden layer with 3 neurons and 1 output, hidden layer uses relu and output layer uses sigmoid

In [17]:
#create model class
import torch
import torch.nn as nn

class Model(nn.Module):
  def __init__(self,num_features):

    super().__init__()

    '''self.linear1 = nn.Linear(num_features, 3)
    self.relu = nn.ReLU()
    self.linear2 = nn.Linear(3,1)
    self.sigmoid = nn.Sigmoid()'''

    super().__init__()
    self.network = nn.Sequential(
        nn.Linear(num_features, 3),
        nn.ReLU(),
        nn.Linear(3, 1),
        nn.Sigmoid()
    )

  def forward(self, features):

    '''out = self.linear1(features)
    out = self.relu(out)
    out = self.linear2(out)
    out = self.sigmoid(out)
    return out''' #use sequential container instead of writing it redundantly like this

    out = self.network(features)




In [12]:
#create dataset
features = torch.rand(10,5)

#create model
model = Model(features.shape[1]) #since the number of input features are 5

#call for forward pass
#model.forward(features)
model(features) # standard way of calling forward

tensor([[0.4133],
        [0.3987],
        [0.4103],
        [0.4016],
        [0.4101],
        [0.4193],
        [0.3987],
        [0.4162],
        [0.4197],
        [0.4059]], grad_fn=<SigmoidBackward0>)

In [15]:
model.linear1.weight

Parameter containing:
tensor([[-2.7011e-01, -3.2515e-04,  1.7002e-01, -1.3016e-01,  1.0750e-01],
        [-5.5611e-02,  6.9478e-02, -2.8362e-01, -1.2906e-01, -1.2231e-01],
        [-2.9017e-01, -3.8809e-01,  2.9367e-01,  2.0186e-02,  2.8883e-01]],
       requires_grad=True)

In [16]:
model.linear2.weight

Parameter containing:
tensor([[0.3000, 0.2328, 0.2013]], requires_grad=True)

In [14]:
from torchinfo import summary
summary(model, input_size = (10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00