In [1]:
import torch
print(torch.__version__)

2.6.0+cu124


In [2]:
if torch.cuda.is_available():
  print("GPU is available")
  print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
  print("GPU not available. Using CPU")

#go to runtime type and change it to T4 GPU

GPU is available
Using GPU: Tesla T4


In [ ]:
# @title Creating Tensors

In [ ]:
#using empty
a = torch.empty(2,3)
#allocates a space of 2,3 and these values are the values that are already present in that space

In [ ]:
#check type
type(a)

torch.Tensor

In [ ]:
#using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
#using rand
torch.rand(2,3)
#this gives different tensor everytime its run
#what if I want same tensor ?

tensor([[0.2476, 0.5165, 0.4500],
        [0.9968, 0.9239, 0.9188]])

In [ ]:
#using seed
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [ ]:
#using tensor
torch.tensor([[1,2,3],[4,5,6]])


tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
#other ways

#using arange
print("using arange -->", torch.arange(0,10,2)) #give start stop step value

#linspace
print("using linspace -->", torch.linspace(0,10,10)) #gets evenly spaced values

#using eye - eye for identity matrix
print("using eye -->", torch.eye(5))

#using full
print("using full -->", torch.full((3,3),5))


using arange --> tensor([0, 2, 4, 6, 8])
using linspace --> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye --> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full --> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


In [ ]:
# @title Tensor Shapes

In [ ]:
x = torch.tensor([[1,2,3],[4,5,6]])

In [ ]:
x.shape

torch.Size([2, 3])

In [ ]:
#creating a tensor with the same size as x
torch.empty_like(x)

tensor([[3616445622929465956, 6066683143785557301, 3617861884435903536],
        [6499591696604936494, 7309453675965983778, 8315168162784306286]])

In [ ]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [ ]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [ ]:
torch.rand_like(x)
#error because rand generates floating point numbers and our x has integer elements

RuntimeError: "check_uniform_bounds" not implemented for 'Long'

In [ ]:
#solution:
torch.rand_like(x, dtype=torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

In [ ]:
# @title Data Types

In [ ]:
#finding data type
x.dtype

torch.int64

In [ ]:
#assign data type
torch.tensor([1.0, 2.0, 3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [ ]:
torch.tensor([1,2,3], dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [ ]:
#using to()
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [ ]:
# @title Mathematical Operations

In [ ]:
# @title 1. Scalar Operations

In [ ]:
x = torch.rand(2,2)
x

tensor([[0.9969, 0.7565],
        [0.2239, 0.3023]])

In [ ]:
#addition
x+2
#subtraction
x-2
#multiplication
x*2
#division
x/2
#integer division
(x*100) // 2
#mod
((x*100) // 2)%2
#power
x**2

#all operations done element wise

tensor([[0.9938, 0.5723],
        [0.0501, 0.0914]])

In [ ]:
# @title 2. Element Wise Operation

In [ ]:
a = torch.rand(2,3)
b = torch.rand(2,3)
print(a)
print(b)
# you can add subtract multiply divide mod etc and they all go element wise

tensor([[0.7909, 0.4235, 0.0169],
        [0.2209, 0.9535, 0.7064]])
tensor([[0.1629, 0.8902, 0.5163],
        [0.0359, 0.6476, 0.3430]])


In [ ]:
c = torch.tensor([1,-2,3,-4])

In [ ]:
#abs
torch.abs(c)

tensor([1, 2, 3, 4])

In [ ]:
#negative
torch.neg(c)

tensor([-1,  2, -3,  4])

In [ ]:
d = torch.tensor([1.9,2.3,3.7,4.4])

In [ ]:
#round
torch.round(d)

tensor([2., 2., 4., 4.])

In [ ]:
#ceil - opp to gif
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [ ]:
#floor - just removes the decimal part
torch.floor(d)

tensor([1., 2., 3., 4.])

In [ ]:
#clamp - rounds off but has boundaries
torch.clamp(d, min=2, max=3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

In [ ]:
# @title 3. Reduction operations

In [ ]:
e = torch.randint(size=(2,3), low=0, high=10)
e

tensor([[7, 9, 2],
        [6, 7, 7]])

In [ ]:
#sum all elements
print(torch.sum(e))
#sum along columns
print(torch.sum(e,dim=0))
#sum along rows
print(torch.sum(e,dim=1))

#remember that 0 refers to columns and 1 refers to rows

tensor(38)
tensor([13, 16,  9])
tensor([18, 20])


In [ ]:
#mean
torch.mean(e, dtype=torch.float32)
#you can calculate along columns and rows similarly

tensor(6.3333)

In [ ]:
#median
torch.median(e)

tensor(7)

In [ ]:
#max and min
print(torch.max(e))
print(torch.min(e))

tensor(9)
tensor(2)


In [ ]:
#product
torch.prod(e)

tensor(37044)

In [ ]:
#standard deviation
torch.std(e.float())

tensor(2.3381)

In [ ]:
#variance
torch.var(e.float())

tensor(5.4667)

In [ ]:
#argmax - gives the position of the max element
torch.argmax(e)

tensor(1)

In [ ]:
#argmin
torch.argmin(e)

tensor(2)

In [3]:
# @title Matrix Operations
f = torch.randint(size=(2,3), low=0, high=10)
g = torch.randint(size=(3,2), low=0, high=10)
print(f)
print(g)

tensor([[2, 1, 5],
        [4, 0, 1]])
tensor([[0, 5],
        [5, 1],
        [6, 7]])


In [4]:
#matrix multiplication
torch.matmul(f,g)

tensor([[35, 46],
        [ 6, 27]])

In [5]:
vector1 = torch.tensor([1,2])
vector2 = torch.tensor([3,4])
#dot product
torch.dot(vector1, vector2)

tensor(11)

In [8]:
#transpose
print(f)
torch.transpose(f,0,1)

tensor([[2, 1, 5],
        [4, 0, 1]])


tensor([[2, 4],
        [1, 0],
        [5, 1]])

In [23]:
#determinant
h = torch.randint(size=(3,3), high=10, low=0, dtype=torch.float32)
print(h)
torch.det(h)

tensor([[9., 6., 7.],
        [1., 1., 3.],
        [6., 5., 8.]])


tensor(-10.0000)

In [12]:
#inverse
torch.inverse(h)

tensor([[-0.0303,  0.1818,  0.0000],
        [ 0.2121, -0.2727,  0.0000],
        [-0.1364,  0.0682,  0.2500]])

In [13]:
# @title Comparison Operations

In [ ]:
#use the normal comparison operators and it gives the boolean values element by element in the matrix

In [14]:
# @title Special functions

In [21]:
k = torch.randint(size=(3,3), high=10, low=0, dtype=torch.float32)
k

tensor([[5., 2., 6.],
        [4., 5., 2.],
        [6., 9., 3.]])

In [17]:
torch.log(k)

tensor([[2.1972, 1.3863, 2.1972],
        [1.6094, 1.3863, 1.7918],
        [1.0986, 2.1972,   -inf]])

In [18]:
torch.exp(k)

tensor([[8.1031e+03, 5.4598e+01, 8.1031e+03],
        [1.4841e+02, 5.4598e+01, 4.0343e+02],
        [2.0086e+01, 8.1031e+03, 1.0000e+00]])

In [19]:
torch.sqrt(k)

tensor([[3.0000, 2.0000, 3.0000],
        [2.2361, 2.0000, 2.4495],
        [1.7321, 3.0000, 0.0000]])

In [20]:
torch.sigmoid(k)

tensor([[0.9999, 0.9820, 0.9999],
        [0.9933, 0.9820, 0.9975],
        [0.9526, 0.9999, 0.5000]])

In [24]:
torch.softmax(k,dim=0)

tensor([[2.4473e-01, 8.9468e-04, 9.3624e-01],
        [9.0031e-02, 1.7970e-02, 1.7148e-02],
        [6.6524e-01, 9.8114e-01, 4.6613e-02]])

In [25]:
torch.relu(k)

tensor([[5., 2., 6.],
        [4., 5., 2.],
        [6., 9., 3.]])

In [27]:
# @title inplace operations

In [28]:
m = torch.rand(2,3)
n=torch.rand(2,3)
print(m)
print(n)

tensor([[0.8200, 0.9416, 0.3987],
        [0.0318, 0.2164, 0.7032]])
tensor([[0.6173, 0.9021, 0.0631],
        [0.0929, 0.5545, 0.0848]])


In [29]:
m.add_(n)
m
#the changes are made to m itself

tensor([[1.4373, 1.8437, 0.4618],
        [0.1247, 0.7709, 0.7880]])

In [30]:
m.relu_()
#m tensor is modified instead of creating new one

tensor([[1.4373, 1.8437, 0.4618],
        [0.1247, 0.7709, 0.7880]])

In [31]:
# @title copying a tensor

In [39]:
a = torch.rand(2,3)
print(a)
b=a
print(b)
a[0][0]=0
print(a)
print(b)
#the changes are seen on b also

tensor([[0.6294, 0.7019, 0.9606],
        [0.7561, 0.8652, 0.1769]])
tensor([[0.6294, 0.7019, 0.9606],
        [0.7561, 0.8652, 0.1769]])
tensor([[0.0000, 0.7019, 0.9606],
        [0.7561, 0.8652, 0.1769]])
tensor([[0.0000, 0.7019, 0.9606],
        [0.7561, 0.8652, 0.1769]])


In [40]:
print(id(a), id(b))
#same memory location

138336069593200 138336069593200


In [44]:
b=a.clone()
a[0][0]=10
print(a)
print(b)
#changes not reflected in b
print(id(a),id(b))

tensor([[10.0000,  0.7019,  0.9606],
        [ 0.7561,  0.8652,  0.1769]])
tensor([[10.0000,  0.7019,  0.9606],
        [ 0.7561,  0.8652,  0.1769]])
138336069593200 138336069537808


In [45]:
# @title tensor operations on gpu

In [46]:
torch.cuda.is_available()

True

In [47]:
device=torch.device('cuda')

In [49]:
#creating new tensor in gpu
torch.rand(size=(2,3),device=device)

tensor([[0.6338, 0.7192, 0.6275],
        [0.2544, 0.7653, 0.0248]], device='cuda:0')

In [51]:
#moving a tensor to gpu
b=a.to(device)

tensor([[10.0000,  0.7019,  0.9606],
        [ 0.7561,  0.8652,  0.1769]], device='cuda:0')

In [52]:
# @title reshaping tensors

In [54]:
u=torch.ones(4,4)
u

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [55]:
#reshape
u.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [56]:
#flatten
u.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [62]:
#permute
v=torch.rand(2,3,4)
#2,3,4 are dimensions 0,1,2
print(v)
print("")
v.permute(2,0,1)
#2,0,1 refer to the dimension (2,3,4 get swapped according to the given order of 2,0,1)
v.permute(2,0,1).shape

tensor([[[0.4643, 0.8991, 0.4452, 0.7371],
         [0.2015, 0.9942, 0.6765, 0.1524],
         [0.8694, 0.4688, 0.0455, 0.3163]],

        [[0.1812, 0.8792, 0.2932, 0.1534],
         [0.7903, 0.3077, 0.7754, 0.7675],
         [0.9756, 0.8119, 0.0750, 0.5996]]])



torch.Size([4, 2, 3])

In [64]:
#unsqueeze
#image size
c=torch.rand(226,226,3)
print(c.unsqueeze(0).shape) #u add a new dimension at 0
print(c.unsqueeze(1).shape)

torch.Size([1, 226, 226, 3])
torch.Size([226, 1, 226, 3])


In [65]:
#squeeze
d=torch.rand(1,20)
d.squeeze(0).shape #removes the dimension at dimension 0

torch.Size([20])

In [66]:
# @title numpy and pytorch

In [67]:
  import numpy as np

In [69]:
a=torch.tensor([1,2,3])
a

tensor([1, 2, 3])

In [74]:
b=a.numpy()
print(type(b))
b


<class 'numpy.ndarray'>


array([1, 2, 3])